openapi: 3.2.0
info:
  description: Fusebit HTTP API for the management and execution of Fusebit accounts, users, functions and more
  version: 1.0.0
  title: Fusebit HTTP API - Integrations Identity/Tags API
  contact:
    email: contact@fusebit.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://api.{region}.on.fusebit.io
  description: Production
  variables:
    region:
      description: 'The region where the API is deployed, for example `''us-west-1''`

        '
      default: us-west-1
security:
- AccessToken: []
tags:
- name: Identity/Tags
paths:
  /v2/account/{accountId}/subscription/{subscriptionId}/connector/{connectorId}/identity/{identityId}/tag:
    parameters:
    - $ref: '#/components/parameters/Account'
    - $ref: '#/components/parameters/Subscription'
    - name: connectorId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/EntityId'
    - name: identityId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/IdentityId'
    get:
      tags:
      - Identity/Tags
      summary: Get the tags for an entity
      operationId: getIdentityTags
      responses:
        200:
          $ref: '#/components/responses/Tag200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
      security:
      - AccessToken:
        - identity:get
  /v2/account/{accountId}/subscription/{subscriptionId}/connector/{connectorId}/identity/{identityId}/tag/{tagKey}:
    parameters:
    - $ref: '#/components/parameters/Account'
    - $ref: '#/components/parameters/Subscription'
    - name: connectorId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/EntityId'
    - $ref: '#/components/parameters/TagKey'
    - name: identityId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/IdentityId'
    get:
      tags:
      - Identity/Tags
      summary: Get the value of a specific tag for an entity
      operationId: getIdentityTag
      responses:
        200:
          $ref: '#/components/responses/TagKey200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
      security:
      - AccessToken:
        - connector:get
  ? /v2/account/{accountId}/subscription/{subscriptionId}/connector/{connectorId}/identity/{identityId}/tag/{tagKey}/{tagValue}
  : parameters:
    - $ref: '#/components/parameters/Account'
    - $ref: '#/components/parameters/Subscription'
    - name: connectorId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/EntityId'
    - name: identityId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/IdentityId'
    - $ref: '#/components/parameters/TagKey'
    - $ref: '#/components/parameters/TagValue'
    put:
      tags:
      - Identity/Tags
      summary: Set the value of a specific tag for an entity
      operationId: putIdentityTag
      responses:
        200:
          $ref: '#/components/responses/Tag200'
        400:
          $ref: '#/components/responses/400'
        403:
          $ref: '#/components/responses/403'
        404:
          $ref: '#/components/responses/404'
      security:
      - AccessToken:
        - connector:put-tag
components:
  responses:
    Tag200:
      description: The set of tags that apply to a specific entity.
      content:
        application/json:
          schema:
            type: object
            required:
            - tags
            properties:
              tags:
                $ref: '#/components/schemas/EntityTags'
              version:
                type: string
          example:
            tags:
              tenantId: Sonicity
    TagKey200:
      description: The requested tag value
      content:
        application/json:
          schema:
            type: string
            description: The value of the requested tag, as a JSON encoded string.
  schemas:
    AccountId:
      type: string
      description: Account id
      example: acc-5555555555555555
    EntityTags:
      type: object
      description: A hash containing tags set on this entity
      example:
        tenant: tenant-525
        customer: Sonicity
    IdentityId:
      type: string
      description: Identity id
      example: ins-01234567890123456789012345678912
    SubscriptionId:
      type: string
      description: Subscription id
      example: sub-5555555555555555
    EntityId:
      type: string
      description: 'The name of an entity, matches: `/^[A-Za-z0-9\-]{1,64}$/)`

        '
  parameters:
    TagKey:
      name: tagKey
      in: path
      required: true
      description: The name of the tag, URL encoded as necessary
      schema:
        type: string
    Subscription:
      name: subscriptionId
      in: path
      required: true
      description: Subscription id
      schema:
        $ref: '#/components/schemas/SubscriptionId'
    TagValue:
      name: tagValue
      in: path
      required: true
      description: The value of the tag, URL encoded as necessary
      schema:
        type: string
    Account:
      name: accountId
      in: path
      required: true
      description: Account id
      schema:
        $ref: '#/components/schemas/AccountId'
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: For a description of the access token format, see [this doc](https://developer.fusebit.io/docs/connecting-fusebit-with-your-application).
